DisablePathCorrection=false
EnablePathEscape=false
FireMethodNotAllowed=true
DisableBodyConsumptionOnUnmarshal=true
TimeFormat="2019-06-29 15:04:05 UTC"
Charset="UTF-8"
PostMaxMemory=67108864

[system]
port=":8080"
logLevel="debug"
environment="dev"
appname="trensy"
cookieHashKey="asdarefsdzc1@#!#13123"
cookieBlockKey="#!@#12312sadadasdada"
timeLocation="Asia/Shanghai"
resourcesPath="./resource"
appTitle="trensy模板"
poweredBy="powered by trensy"

[db]
drive="mysql"
[db.master]
    host="127.0.0.1"
    port= "3306"
    user="root"
    pwd="root123"
    dbname="ling"
    maxIdleConns=5
    maxOpenConns=5
[db.slave]
    host="127.0.0.1"
    port="3306"
    user="root"
    pwd="root123"
    dbname="ling"
    maxIdleConns=5
    maxOpenConns=5
[db.redis]
    network = "tcp"
    addr = "127.0.0.1:6379"
    idleTimeout = 300
    maxActive = 10
    maxIdle = 10
    password = ""
    database = "1"
    prefix =  "trensy_"