DisablePathCorrection=false
EnablePathEscape=false
FireMethodNotAllowed=true
DisableBodyConsumptionOnUnmarshal=true
TimeFormat="2019-06-29 15:04:05 UTC"
Charset="UTF-8"
PostMaxMemory=67108864

[system]
port=":8080"
logLevel="debug"
environment="dev"
appname="duocaiCRM"
cookieHashKey="asdarefsdzc1@#!#13123"
cookieBlockKey="#!@#12312sadadasdada"
timeLocation="Asia/Shanghai"
resourcesPath="./resource"

[db]
drive="mysql"
[db.master]
    host="127.0.0.1"
    port= "3306"
    user="root"
    pwd="root123"
    dbname="article"
    maxIdleConns=5
    maxOpenConns=5
[db.slave]
    host="127.0.0.1"
    port="3306"
    user="root"
    pwd="root123"
    dbname="article"
    maxIdleConns=5
    maxOpenConns=5